In [4]:
import numpy as np
import pandas as pd

# Homework for the DataTalks.Club Machine Learning Zoomcamp
## Week 1: Intro

### Question 1
#### What's the version of NumPy that you installed? 

In [3]:
np.__version__

'1.23.3'

### Getting the data 

In [7]:
df = pd.read_csv('data.csv')
df.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

### Question 2
#### How many records are in the dataset?

In [10]:
df.shape[0]

11914

### Question 3
#### Who are the most frequent car manufacturers (top-3) according to the dataset?

In [22]:
df.groupby('Make')['Make'].value_counts().sort_values(ascending=False).head(3)

Make        Make      
Chevrolet   Chevrolet     1123
Ford        Ford           881
Volkswagen  Volkswagen     809
Name: Make, dtype: int64

### Question 4
#### What's the number of unique Audi car models in the dataset?

In [25]:
df[df['Make'] == 'Audi']['Model'].nunique()

34

### Question 5
#### How many columns in the dataset have missing values?

In [41]:
df.isna().sum()[df.isna().sum() != 0].shape[0]

5

### Question 6

1. Find the median value of "Engine Cylinders" column in the dataset.
2. Next, calculate the most frequent value of the same "Engine Cylinders".
3. Use the `fillna` method to fill the missing values in "Engine Cylinders" with the most frequent value from the previous step.
4. Now, calculate the median value of "Engine Cylinders" once again.

In [50]:
df['Engine Cylinders'].median() # --> 6.0
df['Engine Cylinders'].mode() # --> 4.0
df['Engine Cylinders'].fillna(df['Engine Cylinders'].mode(), inplace=True)
df['Engine Cylinders'].median() # --> no change

6.0

### Question 7

1. Select all the "Lotus" cars from the dataset.
2. Select only columns "Engine HP", "Engine Cylinders".
3. Now drop all duplicated rows using `drop_duplicates` method (you should get a dataframe with 9 rows).
4. Get the underlying NumPy array. Let's call it `X`.
5. Compute matrix-matrix multiplication between the transpose of `X` and `X`. To get the transpose, use `X.T`. Let's call the result `XTX`.
6. Invert `XTX`.
7. Create an array `y` with values `[1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800]`.
8. Multiply the inverse of `XTX` with the transpose of `X`, and then multiply the result by `y`. Call the result `w`.
9. What's the value of the first element of `w`?

In [115]:
lotus_df = df[df['Make'] == 'Lotus']
lotus_df = lotus_df[['Engine HP', 'Engine Cylinders']]
lotus_df = lotus_df.drop_duplicates()
lotus_df

Engine HP  Engine Cylinders
3912      189.0               4.0
3913      218.0               4.0
3918      217.0               4.0
4216      350.0               8.0
4257      400.0               6.0
4259      276.0               6.0
4262      345.0               6.0
4292      257.0               4.0
4293      240.0               4.0

In [116]:
X = lotus_df.values
X

array([[189.,   4.],
       [218.,   4.],
       [217.,   4.],
       [350.,   8.],
       [400.,   6.],
       [276.,   6.],
       [345.,   6.],
       [257.,   4.],
       [240.,   4.]])

In [117]:
XTX = (X.T).dot(X)
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 5.53084235e-05, -2.94319825e-03],
       [-2.94319825e-03,  1.60588447e-01]])

In [118]:
y = np.array([[1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800]])
y.shape

(1, 9)

In [119]:
w = XTX_inv.dot(X.T).dot(y.T)
w

array([[  4.59494481],
       [-63.56432501]])

In [120]:
w[0]

array([4.59494481])